### ISSUE TITLE
result

### ISSUE THREAD

**Issue by tqlblzj** [paulvantieghem/curla#1]
Hi, I trained the model for a long time, about one day on 4080, but I found the car would change lane frequently and the speed sometimes would be more than 100 km/h

**Comment by paulvantieghem** [comment]
Hi, I'm currently experimenting with different augmentations and parameters, so note that the code provided is not final. 

- The frequent lane changing is because the agent benefits more from lane changing than to wait behind other cars. To obtain an agent that behaves differently, try to tune the reward function parameters `lambda_r` that you provide as arguments to `train.py`. To understand which `lambda_r` affects which part of the reward function, have a look at the `reward_function()` function in `carla_env.py`. You could for example set `lambda_r2` and `lambda_r3` to higher values to punish steering angles and lane deviations harder. 
- As for the speeding, the agent only gets a framestack of images as inputs, no speed measurement. This means that the speed of the car has to be determined by the encoder from the distance difference accross the frame stack, which is not trivial. For more accurate speed information, you could try to add the velocity of the vehicle to the latent space by concatinating the velocity measurement with the featues from the encoder. Personally, I also experienced heavy speeding on some episodes, but on average, the agents tend to converge toward the set speed limit of 63 km/h, as can be seen in the image below:

![Screenshot 2023-05-17 at 15 25 37](https://github.com/paulvantieghem/curla/assets/43028370/137a6df7-55ba-4cd9-a84f-60ab0ef431d0)

**Comment by tqlblzj** [comment]
> 

thank you, I will try it myself
